### ISSUE TITLE
Let me copy a position and paste it onto a magic forcefield

### ISSUE THREAD

**Issue by Coldensjo** [hampusborgos/rme#393] opened 2022-04-09 19:17 UTC
![RME_x64_NyqPEhVTZy](https://user-images.githubusercontent.com/102702255/162588584-07dbb639-2145-49dc-95ed-b7a6e767c861.gif)

**Comment by EPuncker** [comment] 2022-04-25 17:30
duplicate of https://github.com/hampusborgos/rme/issues/241

**Closed** 2023-01-23 22:30 UTC
